### ISSUE TITLE
Unreal 5 Support

### ISSUE THREAD

**Issue by visuallization** [atenfyr/UAssetGUI#42] opened 2022-11-07 13:11 UTC
**Is your feature request related to a problem? Please describe.**
Hey there, cool tool! It would be great to also open ue5 uassets? Is it planned to have this option in the future, or is it already somehow working? Currently I get a `System.ArgumentOutOfRangeException` when trying to open an ue5 animation montage uasset.

**Describe the solution you'd like**
Support ue5.

**Describe alternatives you've considered**
I checked if there are other tools out there, but yours seems to be the most actively maintained. 

**Additional context**
![image](https://user-images.githubusercontent.com/6199277/200318611-81dc5cae-5daf-49a9-a63d-2f92a88644c1.png)

**Comment by atenfyr** [comment] 2022-11-09 03:47
Duplicate of atenfyr/UAssetAPI#36

**Closed by atenfyr** 2022-11-09 03:47 UTC
