### ISSUE TITLE
Cannot open Unreal Engine 5 assets

### ISSUE THREAD

**Issue by BonbonFazbear** [atenfyr/UAssetGUI#51] opened 2023-03-01 00:16 UTC
UassetGUI doesn't open unreal engine 5 assets, you should update because there are a lot of games coming to that new version of the engine

Btw that's a awesome asset editor, the best I've ever seen :)

**Comment by atenfyr** [comment] 2023-03-01 00:39
Duplicate of atenfyr/UAssetAPI#36

**Closed by atenfyr** 2023-03-01 00:39 UTC
