### ISSUE TITLE
Cannot open uasset packaged with io store (utoc/ucas)

### ISSUE THREAD

**Issue by Phnxsmv** [atenfyr/UAssetGUI#61] opened 2023-06-06 02:09 UTC
**Describe the bug**
When trying to open an uasset file it causes "Failed to parse this file! System.FormatException: File signature mismatch"

**To Reproduce**
1. Open uasset file

**Expected behavior**
Opening file without exception.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit: 1.0.0.7

**Additional context**
uasset from Gotham Knights. Data from uassets packaged with io store is not split into uasset and uexp. It is contained in one uasset file.
[CMI_BG_GOT_Suit01_Headwear_03.zip](https://github.com/atenfyr/UAssetGUI/files/11659226/CMI_BG_GOT_Suit01_Headwear_03.zip)

**Comment by atenfyr** [comment] 2023-06-06 02:22
Duplicate of atenfyr/UAssetAPI#36

**Closed by atenfyr** 2023-06-06 02:22 UTC
