### ISSUE TITLE
Find feature causes entries to disappear!

### ISSUE THREAD

**Issue by humam2104** [atenfyr/UAssetGUI#90] opened 2024-05-25 06:27 UTC
**Describe the bug**

**To Reproduce**
If you click find multiple times, it searches but leaves everything on the left panel empty for some reason?

**Expected behavior**
These entries should be there, and the results of the search should show up

**Screenshots**
<img width="181" alt="image" src="https://github.com/atenfyr/UAssetGUI/assets/41898465/bcd93e4e-871c-40cd-b237-a617318b6428">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
<img width="248" alt="image" src="https://github.com/atenfyr/UAssetGUI/assets/41898465/c93517c1-00fc-410d-a268-0961b48d495b">

**Additional context**

**Comment by atenfyr** [comment] 2024-06-13 05:16
Duplicate of #68

**Closed by atenfyr** 2024-06-13 05:16 UTC
